// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/alien-defense/TacticalCommandDeck.tsx": () => import("../components/mockups/alien-defense/TacticalCommandDeck.tsx")
};
